// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./components/Card.vue')['default']
    Dark: typeof import('./components/Dark.vue')['default']
    DataTable: typeof import('./components/DataTable.vue')['default']
    FooterContent: typeof import('./components/FooterContent.vue')['default']
    Language: typeof import('./components/Language.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    SideMenu: typeof import('./components/SideMenu.vue')['default']
  }
}

export { }
